# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayBack',
            fields=[
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mysite.Essay')),
                ('id', models.IntegerField(unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('essay_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'essay_back',
                'managed': False,
            },
        ),
    ]
